name: solid_bottom_sheet
description: A full customizable bottom sheet easy to implement. Just put it on your bottomSheet property on your Scaffold widget and see the magic. For more details see the README.md.
version: 0.1.13
repository: https://github.com/dbenitez-bcn/solid_bottom_sheet
issue_tracker: https://github.com/dbenitez-bcn/solid_bottom_sheet/issues

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
